language: objective-c
osx_image: xcode7
script:
  - set -o pipefail
  - xcodebuild -workspace Fusuma.xcworkspace -scheme FusumaExample -sdk iphonesimulator -destination 'name=iPhone 6,OS=9.1' ONLY_ACTIVE_ARCH=NO test

#before_install:
#  - brew update
#  - brew uninstall xctool && brew install --HEAD xctool
